### ISSUE TITLE
Issue with typing bold at the end of link

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-typing#120]
After closing https://github.com/ckeditor/ckeditor5-image/issues/127 there is still an issue with typing at the end of link with bold applied.
1. Go to http://localhost:8125/ckeditor5-presets/tests/manual/article.html (you can disable image feature to be sure that it is no longer the case).
1. Go to the end of the link, activate bold and type some letters.
1. Selection is moved to the beginning of the link.
1. Place caret at the end of the link - error is displayed.

### GIF

![bold-link](https://user-images.githubusercontent.com/2396463/30021062-55d0c204-9166-11e7-913a-fc2888c46724.gif)

**Comment by Reinmar** [comment]
This issue is caused by https://github.com/ckeditor/ckeditor5-engine/issues/1093.

**Comment by Reinmar** [comment]
Caused by https://github.com/ckeditor/ckeditor5-engine/issues/1125.

**Comment by szymonkups** [comment]
After closing this ticket we should remove NOTE from manual test added when solving issue with image captoning: https://github.com/ckeditor/ckeditor5-image/pull/136.

**Comment by f1ames** [comment]
I wasn't able to reproduce the original issue as described, but found very similar ones:

Putting bold at the end of the link and typing:
![mar-14-2018 14-00-28](https://user-images.githubusercontent.com/1061942/37404067-10131cd2-2791-11e8-84ad-dcfeb9b9088a.gif)

Typing when link ends with bold:
![mar-14-2018 14-05-47](https://user-images.githubusercontent.com/1061942/37404090-1e6a07be-2791-11e8-9989-dc8edd390388.gif)

The error in both cases is the same so the cause is probably same/similar.
