### ISSUE TITLE
Incorrect typing result when children mutation handler tries to fix nbsp character

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-typing#170]
## Steps to reproduce

For the following model:

```
<paragraph>
  <text bold="true" linkHref="sth">F[]</text><$text>oo&nbsp;bar</$text>
</paragrah>
```
type something e.g. `x` character .

## Result

Selection went after `&nbsp` character and attributes are applied for the all text before the selection.

```
<paragraph>
  <text bold="true" linkHref="sth">Fxoo []</text><$text>bar</$text>
</paragrah>
```

## Expected result

Selection should be placed after the new character

```
<paragraph>
  <text bold="true" linkHref="sth">Fx[]</$text><$text>oo&nbsp;bar</$text>
</paragrah>
```

**Comment by oskarwrobel** [comment]
See https://github.com/ckeditor/ckeditor5-typing/blob/master/src/utils/injecttypingmutationshandling.js#L94

**Comment by scofalik** [comment]
So, it seemed to me that the problem is in those two lines of code:

```javascript
const newText = modelFromDomChildren.map( item => item.is( 'text' ) ? item.data : '@' ).join( '' ).replace( /\u00A0/g, ' ' );
		const oldText = currentModelChildren.map( item => item.is( 'text' ) ? item.data : '@' ).join( '' );
```

Here we create two text strings which we will compare looking for changes. It seems that `oldText` should also have `&nbsp;` changed to regular spaces for comparison purposes. Of course there always may be some case that I forgot now, but that would make sense. Above those two lines of code is a comment that mentions `_handleTextMutation` function. In that function `oldText` has `&nbsp` replaced.

So I changed that and there are no errors in tests and the bug seems to be fixed 🤷‍♂️ .
