### ISSUE TITLE
[IME] Styling is lost after making composition with enabled inline style

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-typing#188]
Originally reported here - https://github.com/ckeditor/ckeditor5-build-classic/issues/69.

## Steps to reproduce
1. Put the caret in the editor.
1. Change language to Hiragana.
1. Activate bold.
1. Start composition.

## Current result
Styling is lost.

It occurs in all browsers.

**Comment by imyyg** [comment]
Great God, when will this problem be solved? Or is there any temporary solution? Hope to teach @Mgsy

**Comment by Mgsy** [comment]
>Great God, when will this problem be solved? Or is there any temporary solution? Hope to teach @Mgsy

Actually, it turned out that this is a regression and this case was working in CKEditor 5 v11.2.0. We're going to fix it in this iteration and include it to the next CKEditor 5 release.

This bug has been introduced along with this change - https://github.com/ckeditor/ckeditor5-engine/commit/4f9ac0eb4cf83caabea98ca25af279ad31a2d1b7.

**Comment by Reinmar** [comment]
This is a serious issue. @oskarwrobel, is now working on finding a solution. We'll post it here and perhaps release a quick small release of ckeditor5-engine to fix it.

**Comment by oskarwrobel** [comment]
Selection attributes are refreshed after each operation to be sure that selection is always up to date (https://github.com/ckeditor/ckeditor5-engine/issues/1673). A consequence is that attributes are removed from the selection while the composition is in progress.

### What's going on?

1. Executing bold command in the empty editor sets bold attribute as the selection attribute, priority of attribute is `normal` (not `low`) because it is a direct change.
2. Typing the first character adds it to the editor with a bold attribute and moves the selection after the character what resets the priority of selection attributes to `low` (it's no longer a directly set attribute but an attribute set because the previous character is marked as bold).
3. Adding the next character composes it with the previous one, so the previous one is removed, the selection is refreshed and bold is removed from the selection attributes because there is no text with bold around the selection at this stage. Finally, the new, composed character is inserted without any attribute.

**Comment by oskarwrobel** [comment]
We decided to not refresh the selection after each operation (as it was before). It sounds good to have selection up to date after each operation, but it requires some changes for spell checking and composition to remember attributes before replacing text.

**Comment by Reinmar** [comment]
Do you think we could release ckeditor5-engine@13.1.1 with just this change? How unsafe it is?

**Comment by Reinmar** [comment]
👆  @pjasiun @scofalik @Mgsy @oskarwrobel

**Comment by pjasiun** [comment]
I believe the fix should be safe. I am not sure how our environment will handle the fact that the single package is release. Since we use `"^13.1.0"` we should be safe. So theoretically there should be no issues. On the other hand, my intuition tells me that it is a bad idea and something will go wrong, so I would not do it.

**Comment by oskarwrobel** [comment]
From the engine perspective, this fix should be safe.

**Comment by Mgsy** [comment]
I played with the editor a bit during testing and haven't experienced any weird behaviour or regression.
