### ISSUE TITLE
Text transformation removes formatting from a paragraph

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-typing#203]
## Steps to reproduce
1. Add a link to a paragraph.
1. In the same paragraph use text transformation feature.

## Current result

The link is gone.

## GIF

![bug_cke5](https://user-images.githubusercontent.com/20988892/60709771-84a24c00-9f11-11e9-8b9a-22e50204a4c9.gif)

## Additional information

It's happening also for any other formatting.

**Comment by Mgsy** [comment]
The second case reported by @elszczepano:

Steps to reproduce:
1. Add any transformation (e.g. dash or fraction) in a styled part of a paragraph.
2. The whole paragraph is now bold.

![2019-07-05 10 20 49](https://user-images.githubusercontent.com/23155008/60710730-a43a7400-9f13-11e9-83d3-cff72f63b615.gif)

**Comment by mlewand** [comment]
As noted in #206 the issue is more broad and removes just any formatting.

**Comment by scofalik** [comment]
Replacing is incorrectly implemented.

```js
watcher.on( 'matched:data', ( evt, data ) => {
	const selection = editor.model.document.selection;
	const focus = selection.focus;
	const textToReplaceLength = data.text.length;
	const textToInsert = textReplacer( data.text );

	model.enqueueChange( model.createBatch(), writer => {
		const replaceRange = writer.createRange( focus.getShiftedBy( -textToReplaceLength ), focus );

		model.insertContent( writer.createText( textToInsert, selection.getAttributes() ), replaceRange );
	} );
} );
```

Instead of the exact fragment, the whole text is replaced. Additionally, instead of the text node's attributes, selection attributes are set, which is another mistake.

Changes can be introduced either only on `TextTransformation` or in `TextTransformation` and `TextWatcher`. To make the fix simpler and quicker we could start by changing `TextTransformation` only but I dislike that `TextWatcher` in `matched` event returns whole text in `data`. It should return more precise data -- exactly which parts of the text were matched (probably with a position in the model where they happened, because you should not base on selection). For example for `"..."` transformation, this should either fire two `matched` events, or one with two entries in `data`, each stating that `"` should be changed to nice quote, with the position in the model.

To have the fix sooner, we could, for now, make changes only in `TextTransformation`.

First, all transformations should be normalized to regexps with capturing groups. Second, `data` from `matched` event should be tested against given regexp. Then, basing on match results and current selection position, we should replace only exactly the parts of texts that changed.

As far as configuration goes, the format should be something like:

```
quotesPrimary: {
    // This is quite similar to what we have now.
    from: buildQuotesRegExp( /(")([^"]*)(")$/ ),
    to: [ '“', null, '“' ]
};
```

This gives you info that only the first and the third match should be replaced, while the second should be left as is. This way it is possible to make exact changes (and also use proper attributes taken from nodes at evaluated positions).

**Comment by Reinmar** [comment]
> As far as configuration goes, the format should be something like:

Do we need something that complicated? Can't we use `diff()` to figure out which pieces changed?

**Comment by scofalik** [comment]
I thought the diff would be more difficult. Also... honestly... after all the problems with non-exact diffs, I am not sure if I want to go that route.

**Comment by Reinmar** [comment]
> I thought the diff would be more complicated. Also... honestly... after all the problems with non-exact diffs, I am not sure if I want to go that route.

More complicated for us, but less for the developers. But I could live with the array too, because it will be required only in the most complex cases only. However, I don't think that it will actually help you in any way because it only affects the piece that's being matched. While the problem in this issue is actually how to replace only the part that's being matched, so differentiating it from the rest of the text which isn't touched.

Anyway, both fine for me. Just don't make the config too complex for people.

**Comment by scofalik** [comment]
I really don't want to have anything to do with `diff()` if I can avoid it.

**Comment by Reinmar** [comment]
Please remember about https://github.com/ckeditor/ckeditor5-typing/issues/196, though. Your fix should anticipate that extension.
