### ISSUE TITLE
Error while typing after applying an attribute

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-typing#39]
1. Open https://ckeditor5.github.io/.
2. Double click the first word in the editor.
3. Apply bold.
4. Start typing.

An error is thrown:

```
ckeditor.min.js:4 Uncaught TypeError: Cannot read property 'parent' of null
```

**Comment by oskarwrobel** [comment]
I'm having the same error working on linking.

![link2](https://cloud.githubusercontent.com/assets/1057056/17738431/872005de-6491-11e6-8c3f-ab01ffa2617d.gif)

![screenshot 2016-08-17 15 35 39](https://cloud.githubusercontent.com/assets/1057056/17738224/b4df2c4e-6490-11e6-95a5-8761b6f86387.png)

**Comment by Reinmar** [comment]
Another case that must be checked:

1. Open http://tests.ckeditor.dev:1030/build/modules/amd/tests/enter/manual/enter
2. Double click any of the "Heading" words.
3. Type any letter.

The same error is thrown.

@oskarwrobel, please remember about creating MTs for these issues (preferably all mentioned here). Tag them `ticket, 0.3.0, 39`.

**Comment by scofalik** [comment]
I am leaving here a note in cause I won't be able to get back to this issue in nearest future:

I don't know if this is true for all reported cases, because I wasn't able to reproduce PK's examples. In case of Oskar's Link bug, the problem lies here: https://github.com/ckeditor/ckeditor5-typing/blob/master/src/input.js#L174-L189

As you can see, in this loop, we may have multiple operations (insert/delete) on a text node. These operations are then reflected on model and conversion changes the view afterwards. As you can see, `viewPos` is created each time, using `mutation.node` (which is a view text node). In second and next iterations of that loop it appears, that `viewPos` cannot be mapped (error is thrown). This is beacuse `mutation.node` is not mapped. I suspect that this is because after first change, `mutation.node` may be already removed from the view tree (because it got replaced by updated text node).

I that's the case, I see two solutions:
1. We somehow refresh `mutation.node` or map `mutation.node` parent to model element or something. We need to do something to have stable point of reference.
2. We don't do each change in single step but instead replace whole text. If we replace whole text node in the view anyway maybe there's no difference whether we do changes each on it's own, or apply all of them at once. Heck, it could be even more efficient to do all the changes at once.

**Comment by Reinmar** [comment]
Works fine now.
